config/routes.rb
Transources::Application.routes.draw do

  resources :resources do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
      get 'search_all'
      get 'tag/:tag_id', to: "resources#tag"
    end
  end

  get "tags/categories", to: "tags#categories"

  resources :comments, only: [:destroy] do
    collection do
      get "manage"
    end
    member do
      get 'spam'
      get 'ham'
    end
  end

  root :to => "home#index"
  devise_for :users
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Rakismet::Model
  attr_accessor :anonymous
  belongs_to :resource

  belongs_to :user

  validates_presence_of :resource_id

  rakismet_attrs  author: ->(c) { c.user ? c.user.name : "" }, 
                  author_email: ->(c) { c.user ? c.user.email : "" },
                  comment_type: "comment",
                  content: :text#,
                  #permalink: ->(c) { Rails.application.routes.url_helpers.resource_path(id: c.resource.id, only_path: false) }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    authorize @comment
    @resource = Resource.find(params[:resource_id])

    @comment.resource = @resource
    @comment.user_ip = request.remote_ip
    @comment.user_agent = request.headers["User-Agent"]
    @comment.referrer = request.headers["Referer"]


    if params[:comment][:anonymous] == "0"
      @comment.user_id = current_user.id
    end

    @comment.spam = @comment.spam?

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @resource, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @resource }
      else
        format.html { render controller: "resource", action: "show" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize @comment
    @resource = Resource.find(params[:resource_id]) if params[:resource_id].present?

    @comment.destroy

    respond_to do |format|
      format.html {
        if @resource
          redirect_to @resource
        else
          redirect_to manage_comments_path
        end
      }
      format.json { head :no_content }
    end
  end

  def manage
    @comments = Comment.order(created_at: :desc)
    if params[:resource_id].present?
      @comments = @comments.where(resource_id: params[:resource_id])
      @resource = Resource.find(params[:resource_id])
    end

    if params[:spam].present?
      @comments = @comments.where(spam: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(params[:spam]))
    end
    authorize @comments
  end

  def spam
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.spam = @comment.spam!
    @comment.save
    redirect_to :back
  end

  def ham
    @comment = Comment.find(params[:id])
    authorize @comment
    @comment.spam = @comment.ham!
    @comment.save
    redirect_to :back
  end

private

  def comment_params
    params.require(:comment).permit(:user_id, :text, :score, :resource_id).except(:anonymous)
  end
end

app/views/comments/manage.html.haml
.row
  .col-xs-12.col-sm-3.pull-right
    %h3= t('comments.filter')
    %p
      = form_tag manage_comments_path, method: :get, class: "form" do
        .form-group
          = label_tag :resource_id
          - if @resource
            = hidden_field_tag :resource_id, @resource.id, class: "select2 ajax", data: { source: search_all_resources_path, text: "#{@resource.title} (#{@resource.town})" }, style: "width: 100%"
          - else
            = hidden_field_tag :resource_id, "", class: "select2 ajax", data: { source: search_all_resources_path }, style: "width: 100%"
        .form-group
          = label_tag :spam
          = select_tag :spam, options_for_select(["true", "false"], params[:spam]), prompt: "All"
        = submit_tag t('common.actions.filter'), class: "btn btn-default"

  .col-xs-12.col-sm-9
    %table.table.table-striped.table-bordered#comments_table
      %thead
        %tr
          %th= t('resources.description')
          %th= t('comments.text')
          %th= t('comments.author')
          %th= t('comments.date')
          %th= t('comments.spam')
          %th= t('common.actions.description')
      %tbody
        - @comments.each do |c|
          %tr
            %td= link_to c.resource.title, c.resource
            %td.comment_text{data: {content: c.text, trigger: "hover", placement: "bottom", container: "body"}}
              = truncate(c.text, length: 20)
            %td= c.user ? c.user.name : t('common.anonymous')
            %td= c.created_at
            %td= c.spam
            %td
              .dropdown
                %a.js-dropdown{id: "#{c.id}_dropdown", data: {toggle: "dropdown"}, href: "#"}= t('common.actions.description')
                %ul.dropdown-menu{role: "menu", aria: {labelledby: "#{c.id}_dropdown"}}
                  %li= link_to t('common.actions.delete'), c, method: "delete"
                  - if c.spam
                    %li= link_to t('common.actions.ham'), ham_comment_path(c)
                  - else
                    %li= link_to t('common.actions.spam'), spam_comment_path(c)