config/routes.rb
Transources::Application.routes.draw do

  resources :resources do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
      get 'search_all'
      get 'tag/:tag_id', to: "resources#tag"
    end
  end

  get "tags/categories", to: "tags#categories"

  resources :comments, only: [:destroy] do
    collection do
      get "manage"
    end
    member do
      get 'spam'
      get 'ham'
    end
  end

  root :to => "home#index"
  devise_for :users
end

app/views/resources/_comments.html.haml
%h4= t('comments.description')
- if @resource.comments.empty?
  .no-comments
    %p= t('comments.none')
- else
  .comments
    - @resource.comments.each do |c|
      -unless c.spam?
        .comment.well
          .body
            = c.text
          .info
            %small
              - if c.user
                = c.user.name
              - else
                = t('common.anonymous')
              &middot;
              = c.created_at
          - if policy(c).destroy?
            .actions
              = form_tag resource_comment_path(@resource, c), method: :delete do
                = submit_tag t('common.actions.delete'), class: "btn btn-link btn-xs"


= simple_form_for([@resource, Comment.new()], html: { class: "form-horizontal" }) do |f|
  = f.error_notification

  .form-group
    .col-xs-12
      = f.input_field :text, style: "width: 100%;", rows: 5
  .checkbox
    %label
      = f.check_box :anonymous
      = t('comments.anonymous_prompt')
  = f.button :submit, class: "btn btn-primary"

app/views/resources/_form.html.haml
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GMAPS_API_KEY']}&sensor=false"

#errors

= simple_form_for(@resource, html: { class: 'edit_resource' }) do |f|
  = f.error_notification

  .form-inputs.row
    .col-md-6.col-xs-12
      = f.input :title
      = f.input :description, input_html: { rows: 5, cols: 40 }
      = f.input :category_list
    .col-md-6.col-xs-12
      = f.input :address_line_1
      = f.input :address_line_2
      = f.input :town
      = f.input :country
      = f.input :lat, as: :hidden
      = f.input :long, as: :hidden


  .form-actions.row
    .col-xs-12
      = f.button :submit, onclick: 'return GetLatLong();', class: "btn btn-primary"

app/views/resources/_search_form.html.haml
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?libraries=places&key=#{ENV['GMAPS_API_KEY']}&sensor=false"

#alert

.row
  .col-xs-6
    %h3= t('common.actions.search')
    = form_tag search_resources_path, method: :post, remote: true do
      .row.form-group
        .col-xs-12
          %p.form-control-static= t('resources.search_prompt')
      .row.form-group
        .col-xs-12
          = label_tag 'categories', t('resources.categories'), class: 'sr-only'
          = select_tag 'categories', options_from_collection_for_select(categories, "name", "name"), multiple: true, style: "display: block;"
      .row.form-group
        .col-xs-12.col-md-5
          = label_tag 'location', t('resources.location.description'), class: 'sr-only'
          .input-group
            %span.input-group-addon= t('resources.location.prepend')
            = text_field_tag 'location', nil, class: "form-control js-location-autocomplete"
        .col-xs-12.col-md-5
          = label_tag 'radius', t('resources.radius.description'), class: 'sr-only'
          .input-group
            %span.input-group-addon= t('resources.radius.prepend')
            = number_field_tag 'radius', 20, min: 1, class: "form-control"
            %span.input-group-addon= t('resources.radius.append')
        .col-xs-12.col-md-2
          = button_tag "Search", class: "btn btn-primary js-location-search", type: "button", data: { "loading-text" => t('resources.searching') }

.row
  .col-md-6.col-xs-12
    .results-map
  .col-md-6.col-xs-12
    %ul.results-list.list-unstyled

app/views/resources/edit.html.haml
%h1= t('resources.edit')

= render 'form'

app/views/resources/index.html.haml
= javascript_include_tag "search_form"

= render partial: "resources/search_form", locals: {categories: @categories}

app/views/resources/new.html.haml
%h1= t('resources.new')

= render 'form'

app/views/resources/show.html.haml
= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GMAPS_API_KEY']}&sensor=false"

.row
  .col-md-6.col-xs-12
    %h1
      = @resource.title
    
    %p.lead= @resource.description
    .row
      .col-xs-6
        %p
          %strong= "#{t('resources.categories')}:"
          = @resource.categories.map { |c| c.name }.join(', ')

        %p!= @resource.join_address("<br>")
      .col-xs-6
        %a.btn.btn-default.btn-xs{href: url_for(edit_resource_path(@resource))}
          %i.glyphicon.glyphicon-edit
          = t('common.actions.edit')

    .map{data: {lat: @resource.lat, long: @resource.long}}

    

  .col-md-6.col-xs-12
    -# Comments/Reviews
    = render "comments", locals: {resource: @resource}

app/views/resources/tag.html.haml
%ul
  - @resources.each do |r|
    %li= link_to r.title, r