config/routes.rb
Transources::Application.routes.draw do

  resources :resources do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
      get 'search_all'
      get 'tag/:tag_id', to: "resources#tag"
    end
  end

  get "tags/categories", to: "tags#categories"

  resources :comments, only: [:destroy] do
    collection do
      get "manage"
    end
    member do
      get 'spam'
      get 'ham'
    end
  end

  root :to => "home#index"
  devise_for :users
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar-header
  %button.navbar-toggle{ type: "button", data: { toggle: "collapse", target: ".navbar-1-collapse" } }
    %span.sr-only Toggle navigation
    %span.icon-bar
    %span.icon-bar
    %span.icon-bar
  = link_to "Transources", root_path, :class => 'navbar-brand'
.collapse.navbar-collapse.navbar-1-collapse
  %ul.nav.navbar-nav
    - if user_signed_in?
      %li
        = link_to t('sessions.logout'), destroy_user_session_path, :method=>'delete'
    - else
      %li
        = link_to t('sessions.login'), new_user_session_path
    - if user_signed_in?
      %li
        = link_to t('registrations.edit'), edit_user_registration_path
    - else
      %li
        = link_to t('registrations.new'), new_user_registration_path
    %li.dropdown
      %a.dropdown-toggle{href: "#", data: { toggle: "dropdown"}}
        = t('resources.description')
        %b.caret
      %ul.dropdown-menu
        %li
          = link_to t('common.actions.search'), root_path
        %li
          = link_to t('common.actions.new'), new_resource_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    %title= content_for?(:title) ? yield(:title) : "Transources"
    %meta{:content => content_for?(:description) ? yield(:description) : "Transources", :name => "description"}
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = javascript_include_tag controller_name if asset_path(controller_name) and Rails.application.assets.find_asset(controller_name)
    = csrf_meta_tags
    = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %nav.navbar.navbar-default.navbar-fixed-top{role: "navigation"}
      = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .col-xs-12
            = render 'layouts/messages'
            = yield
        %footer
      / ! end of .container
    / ! end of #main